/*
 * directory_manager.c
 *
 *  Created on: 1 Oct 2017
 *      Author: Andrea Graziani
 */

/* Including project header files */
/* ============================================================================ */
#include "../project_property.h"

/* Including libraries */
/* ============================================================================ */
#include <pwd.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>
#include <errno.h>
#include <dirent.h>
#include <stdio.h>
#include <assert.h>

/* Macro */
#define APPLICATION_MAIN_FOLDER "ClientServerApplication"

/*
 * This function is used to check existence of a specified directory.
 * If latter doesn't exits, it will be created.
 *
 * @direcotry
 */
void __check_directory(const char *directory) {

#ifdef TEST
	fprintf(stderr, "DEBUG_CHECK_DIRECTORY: 'directory': %s\n", directory);
#endif

	/*
	 * The 'opendir()' function opens the directory specified by dirpath and returns a
	 * pointer to a structure of type DIR.
	 */
	errno = 0;
	DIR *dir_stream = opendir(directory);
	if (dir_stream == NULL) {

		/*
		 * Check errno value:
		 * ENOENT: A directory component in pathname does not exist or is a dangling symbolic link.
		 */
		if (errno == ENOENT) {
			if (mkdir(directory, S_IRWXU | S_IRWXG | S_IROTH | S_IXOTH) == -1)
				exit_failure("mkdir");
		} else
			exit_failure("opendir");
	} else {

#ifdef TEST
		assert(dir_stream != NULL);
#endif

		/* This function closes the directory stream dirstream. */
		if (closedir(dir_stream) == -1)
			exit_failure("closedir");
	}
}

/*
 * This function is used to get apllication main directory
 */
char *__get_application_main_directory() {

	/* Application directory */
	char *application_main_directory;
	/* Number of characters generated by 'snprintf' */
	int n = 0;

	/* Get user ID */
	uid_t user_id = getuid();

	/* 'passwd' structure is defined in '<pwd.h>' */
	struct passwd *passwdEnt = getpwuid(user_id);

#ifdef TEST
	assert(passwdEnt != NULL);
	fprintf(stderr, "DEBUG_GET_APPLICATION_MAIN_DIRECTORY: 'passwdEnt->pw_dir': %s\n",
			passwdEnt->pw_dir);
#endif

	/* Calc memory size */
	n = snprintf(NULL, 0, "%s/%s", passwdEnt->pw_dir,
	APPLICATION_MAIN_FOLDER);
	if (n == -1)
		exit_failure("snprintf");

	/* Allocation memory */
	application_main_directory = calloc(n + 1, sizeof(char));
	if (application_main_directory == NULL)
		exit_failure("calloc");

	/* Generate output */
	if (snprintf(application_main_directory, n + 1, "%s/%s", passwdEnt->pw_dir,
	APPLICATION_MAIN_FOLDER) != n)
		exit_failure("snprintf");

#ifdef TEST
	assert(application_main_directory != NULL);
	fprintf(stderr,
			"DEBUG_GET_APPLICATION_MAIN_DIRECTORY: 'application_main_directory': %s\n",
			application_main_directory);
#endif

	/* Check directory */
	__check_directory(application_main_directory);

	return application_main_directory;
}

/*
 * Get application directory folder
 * @folder: It represents folder name
 */
char *get_application_directory(char *folder) {

	/* Number of characters generated by 'snprintf' */
	int n = 0;
	/* Output */
	char *output;
	/* Application main directory */
	char *application_main_directory = __get_application_main_directory();

	/* Calc memory size */
	n = snprintf(NULL, 0, "%s/%s", application_main_directory, folder);
	if (n == -1)
		exit_failure("snprintf");

	/* Allocation memory */
	output = calloc(n + 1, sizeof(char));
	if (application_main_directory == NULL)
		exit_failure("calloc");

	/* Generate output */
	if (snprintf(output, n + 1, "%s/%s", application_main_directory, folder) != n)
		exit_failure("snprintf");

	/* Free unuseful memory */
	free(application_main_directory);

	/* Check directory */
	__check_directory(output);

#ifdef TEST
	fprintf(stderr, "DEBUG_GET_APPLICATION_DIRECTORY: 'output': %s\n", output);
#endif

	return output;
}

